### ISSUE TITLE
False-positive tooltip appearance

### ISSUE THREAD

**Issue by helperman** [magic-FE/translate-man#38]
Another issue with the plugin is lots of false positives.
I mean a tooltip with translation appears even when mouse cursor is not over any word.

See what I mean on these video.
I expect tooltip do not appear in such cases:
https://www.youtube.com/watch?v=cvOuPKW8Qbw

Test page:
https://en.wikipedia.org/wiki/Team_Foundation_Server

**Comment by cloudIC** [comment]
fixed in v3.0.7

**Comment by helperman** [comment]
Wiikipedia fixed excellent!
But many other sites still have this issue:
http://storage3.static.itmages.ru/i/18/0403/h_1522738366_3251230_c67e89ff4c.png
